### ISSUE TITLE
expected type-id as the default parameter for a type-parameter

### ISSUE THREAD

**Issue by seanbaxter** [TartanLlama/ranges#1]
https://github.com/TartanLlama/ranges/blob/main/include/tl/to.hpp#L99

Hi Sy, I'm trying to compile your code and have run up against this line. Is `typename` required before ContainerType's default type?

```cpp
template<int X>
struct foo;

template<int X, typename Y = foo<X>::type>
struct bar;
```

This is the same thing. It compiles with gcc and msvc but breaks with clang. Is this a context in which typename is relaxed for C++20, or is it a bug? Just asking so I can make the changes in my compiler if needed.

http://eel.is/c++draft/temp.res#general-4.2.5

I _think_ this is a relaxed typename context, but it surprises me that clang trunk doesn't get this basic scenario right.

**Comment by TartanLlama** [comment]
I think it should be valid by those rules, but I'm happy to add a `typename` there to make things easier.
