### ISSUE TITLE
zip.hpp not compiling on clang

### ISSUE THREAD

**Issue by A-F-V** [TartanLlama/ranges#20]
In Godbolt, I have imported zip.hpp (by manualling copy and pasting)

https://godbolt.org/z/vrcaP6jbj

**Not compiling in clang** :
- ` error: missing 'typename' prior to dependent type name 'detail::tuple_or_pair_impl<Ts...>::type'
   using tuple_or_pair = detail::tuple_or_pair_impl<Ts...>::type;`

This may be related to another issue I have had using zip with std::view and it failing to compile (in MSCV) because of some indecipherable templating error

**Comment by TartanLlama** [comment]
This should be fixed as of https://github.com/TartanLlama/ranges/commit/40ba5057de775d3d7218ac9975196868d22bf052
